name: 'ngx-mitaa publish'

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: cd dist/ngx-mitaa && npm publish --access public
         env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
